import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import styles from "./Layout.module.css";
import Link from "next/link";
import Providers from "./Providers";
import HeaderSession from "./components/headerSession/HeaderSession";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={styles.container}>
        <Providers>
        {/* HEADER */}
        <header className={styles.header}>
          <div className={styles.logo}>Your Next Store</div>
          <nav className={styles.nav}>
            <Link href={'/dashboard'}>Accessories</Link>
            <Link href={'/dashboard'}>Celulares</Link>
            <Link href={'/sendEmail'}>Enviar Email</Link>
          </nav>

            <HeaderSession />
  
          <div className={styles.search}>
            <input type="text" placeholder="Search for products..." />
            <button>🔍</button>
          </div>
        </header>

        {/* MAIN */}
         <main className={styles.main}>{children}</main>
        </Providers>
        {/* FOOTER */}
        <footer className={styles.footer}>
          <div className={styles.footerTop}>
            <p>© 2025 YNS Demo. All rights reserved.</p>
            <div className={styles.social}>
              <span>🌐</span>
              <span>📸</span>
              <span>💼</span>
            </div>
          </div>
          <div className={styles.footerBottom}>
            <nav>
              <Link href={'/'}>Accessories</Link>
              <Link href={'/'}>Celulares</Link>
              <Link href={'/'}>Tecnologia</Link>
            </nav>
            <div className={styles.subscribe}>
              <input type="email" placeholder="Enter your email" />
              <button>Subscribe</button>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}

